// <auto-generated />
namespace PRSweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleterequirementforTotalinPurchaseRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleterequirementforTotalinPurchaseRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201710041809027_delete requirement for Total in Purchase Request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
